version: '3'
services:
  sarah:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./api:/sarah/api
      - ./src:/sarah/src
      - ./server.js:/sarah/server.js
      - ./config.json:/sarah/config.json
      - ./assets:/sarah/assets
