version: '3'
services:
  sarah:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NPM_INSTALL_ARGS: "--omit=dev"
    restart: always
    volumes:
      - ./api:/sarah/api
      - ./src:/sarah/src
      - ./server.js:/sarah/server.js
      - ./config.json:/sarah/config.json
      - ./assets:/sarah/assets

networks:
  default:
    external:
      name: sce
