name: Discord Bot Tests
      
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: cache dependencies
      id: discord-bot-cache
      uses: actions/cache@v4
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: install dependencies if cache miss
      if: steps.discord-bot-cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
    - run: npm run lint
